### ISSUE TITLE
Give the playbook a useful domain

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/design-system-team-docs#64]
It came up in our first show & tell of 2024 that being able to visit the playbook at https://team-playbook.design-system.service.gov.uk would be useful.

**Comment by 36degrees** [comment]
Ran this past SMT just to check they were happy with this and got the A-OK – there's plenty of prior art for this elsewhere.

I've raised #65 just to try and make it really clear that it's internal. Once that's merged I'll set it up in Netlify.

**Comment by 36degrees** [comment]
This is done 🎉
